# Generated by Django 4.2 on 2023-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zing_It_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
